name: Code Review

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build_and_add_comments:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # BASE_SHA: ${{ github.event.pull_request.base.sha }}
      # GITHUB_SHA: ${{ github.sha }}
      # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # CLOUDFLARE_WORKER_HEALTH_URL: ${{ secrets.CLOUDFLARE_WORKER_HEALTH_URL }}

    steps:
      - name: Initialize
        run: echo running actions...

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 18
        
      - name: Install dependencies
        run: npm install

      - name: Build Typescript
        run: npm run build
      
      - name: Run Tests
        run: npm run test

      - name: Auto Comments
        run: echo add comments...
